### PR TITLE
chore: update buildkit fork to v0.12.5 (PLAT-351)

### PR DESCRIPTION
**Pull request by jpf-okteto**

### CODE REVIEW

**Comment by ifbyol** [comment]
> ```
> # github.com/depot/depot-go/machine
> ../../go/pkg/mod/github.com/depot/depot-go@v0.1.0/machine/machine.go:182:58: too many arguments in call to client.WithCredentials
> 	have (string, string, string, string)
> 	want (string, string)
> # github.com/moby/buildkit/frontend/dockerfile/instructions
> ../../go/pkg/mod/github.com/okteto/buildkit@v0.0.0-20240218144646-8aaa190e7284/frontend/dockerfile/instructions/parse.go:592:15: healthcheck.StartInterval undefined (type container.HealthConfig has no field or method StartInterval)
> ```
> 
> depot/depot-go depends on moby/buildkit v0.11.6.
> 
> moby/buildkit v0.12 changed the definition for one of its ClientOpt functions.
> 
> This error could be solved in two ways:
> 
> * Wait until depot/depot-go updates its moby/buildkit dependency to v0.12 and uses the new ClientOpt function
>   
>   * [Bump github.com/moby/buildkit from 0.11.6 to 0.12.5 depot/depot-go#18](https://github.com/depot/depot-go/pull/18)
> * We revert the ClientOpt signature in our fork of moby/buildkit (okteto/buildkit) to v0.11.

@jpf-okteto Does client 0.11 works well with server 0.12? If so, I would wait until depot updates the dependency

**Comment by ifbyol** [comment]
> @ifbyol yes, lgtm, let's wait until depot updates their dependency too. I think we can keep the draft pr open meanwhile.
> 
> I wanted to open the draft PR as it involves a few extra changes so context wasn't lost.

Ok! Thanks!

**Comment by pchico83** [comment]
@jpf-okteto looks like depot just pushed the tag 2.0 that uses buildkit 0.12.5:
https://github.com/depot/depot-go/releases/tag/v0.2.0

**Comment by ifbyol** [comment]
I would say to go with 3rd (leave the `docker/docker` downgrade) or 2nd option (do the change in our fork).

I'd explore which potential CVE we would have with the `docker/docker` downgrade and evaluate according to that. If there are known vulnerabilities, we could go with upgrading our fork

**Comment by andreafalzetti** [comment]
@jpf-okteto I agree on the downgrade and evaluate from there. In the meantime perhaps nudge for upgrade in `moby/buildkit`

**Review by ifbyol — COMMENTED** [review]
Looks good to me, but I would wait until @jLopezbarb or @andreafalzetti review. They have more knowledge and context

**Review by pchico83 — APPROVED** [review]
